server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location = /env-config.js {
        default_type "application/javascript";
        return 200 'window.ENV_CONFIG = {
            API_BASE_URL: "$API_BASE_URL",
            LOGIN_URL: "$LOGIN_URL",
            MINIO_URL: "$MINIO_URL",
            RABBIT_URL: "$RABBIT_URL",
            SWAGGER_URL: "$SWAGGER_URL",
            DOZZLE_URL: "$DOZZLE_URL"
        };';
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}